name: Build
on: [push]
jobs:
  release:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Build artifacts
        run: |
          rm ardwiino_script_post.py
          rm -rf .git
          rm *.md
          rm LICENSE
          rm .gitignore
          rm -r .github
          mv ardwiino_script_post_tool.py ardwiino_script_post.py
          cd ..
          tar cfJ firmware.tar.xz Santroller
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          prerelease: true
          name: "Latest Build"
          files: "../firmware.tar.xz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}