name: Build project

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: "recursive" 
    - name: setup
      run: |
        sudo apt-get install -y make gcc-avr avr-libc binutils
    - name: make
      run: make build-all
    - uses: actions/upload-artifact@v1
      with:
        name: firmware
        path: output
    - name: release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: output/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
